INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_URMETEASYREAD urmetEasyRead)

FIND_PATH(
    URMETEASYREAD_INCLUDE_DIRS
    NAMES urmetEasyRead/api.h
    HINTS $ENV{URMETEASYREAD_DIR}/include
        ${PC_URMETEASYREAD_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    URMETEASYREAD_LIBRARIES
    NAMES gnuradio-urmetEasyRead
    HINTS $ENV{URMETEASYREAD_DIR}/lib
        ${PC_URMETEASYREAD_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(URMETEASYREAD DEFAULT_MSG URMETEASYREAD_LIBRARIES URMETEASYREAD_INCLUDE_DIRS)
MARK_AS_ADVANCED(URMETEASYREAD_LIBRARIES URMETEASYREAD_INCLUDE_DIRS)

